# Generated by Django 4.2.7 on 2023-11-20 16:30
# mypy: ignore-errors

from django.db import migrations, models
import users.constants


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("AD", "AD"), ("SR", "SR"), ("JR", "JR")],
                default=users.constants.Role["JUNIOR"],
                max_length=2,
            ),
        ),
    ]
