# Generated by Django 4.2.6 on 2023-10-31 19:40
# mypy: ignore-errors
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issues",
        ),
    ]
