name: Code quality

on: [pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install ruff black isort mypy pydantic
    - name: Run linter
      run: ruff check . && mypy . 
    - name: Run formatters
      run: black --check -t py311 . && isort .   